# Generated by Django 3.2.7 on 2021-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='n', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
